version : '3'
services : 
  web:  
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    volumes: 
      - .:/app 
#      - /app/nodes_modules
  tests:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes: 
      - .:/app 
#      - /app/nodes_modules
    command: ["npm", "run", "test"]


